sudo: required
services:
  - docker

before_install:
  - docker build -t lai110771/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true lai110771/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-975050378575"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

  